version: '2'
services:
  auth:
    container_name: auth
    image: auth
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      GOOGLE_CLIENT_ID: "google_client_id"
      MONGODB_URI: "mongodb://mongo:password@mongo:27017/?retryWrites=true&w=majority"
    restart: always
