version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - spring
    volumes:
      - auth-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    restart: always
  auth:
    container_name: auth
    image: auth
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - spring
    depends_on:
      - mongo
    environment:
      GOOGLE_CLIENT_ID: "google_client_id"
      MONGODB_URI: "mongodb://mongo:password@mongo:27017/?retryWrites=true&w=majority"
      SECRET_KEY: "jwt_secret_key_placeholder"
      API_KEYS: "api_key_placeholder1,api_key_placeholder2,api_key_placeholder3"
      PROFILE: "dev"
    restart: always
networks:
  spring:
volumes:
  auth-mongo-data:
